CREATE TABLE matriculas.capacidad_oferta (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rbd integer NOT NULL,
  anio_escolar integer NOT NULL,
  nivel_str text NOT NULL,
  capacidad_sala integer NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT capacidad_oferta_unica UNIQUE (rbd, anio_escolar, nivel_str)
);
CREATE INDEX idx_capacidad_oferta_lookup ON matriculas.capacidad_oferta(rbd, anio_escolar, nivel_str);;
