CREATE SCHEMA IF NOT EXISTS matriculas;

-- Catalogos
CREATE TABLE matriculas.catalogo_grado (
    codigo integer NOT NULL,
    descripcion character varying(100) NOT NULL,
    CONSTRAINT catalogo_grado_pkey PRIMARY KEY (codigo)
);

CREATE TABLE matriculas.catalogo_tipo_ensenanza (
    codigo integer NOT NULL,
    descripcion character varying(255) NOT NULL,
    CONSTRAINT catalogo_tipo_ensenanza_pkey PRIMARY KEY (codigo)
);

-- Apoderado
CREATE TABLE matriculas.apoderado (
    id_apoderado integer GENERATED BY DEFAULT AS IDENTITY,
    rut_pasaporte character varying(20) NOT NULL,
    nombres character varying(100) NOT NULL,
    apellido_paterno character varying(100) NOT NULL,
    apellido_materno character varying(100),
    domicilio character varying(255) NOT NULL,
    telefono character varying(20),
    correo_electronico character varying(100),
    CONSTRAINT apoderado_pkey PRIMARY KEY (id_apoderado),
    CONSTRAINT apoderado_rut_pasaporte_key UNIQUE (rut_pasaporte)
);

-- Establecimiento (con enlace por RBD a public.slep_establecimientos)
CREATE TABLE matriculas.establecimiento (
    id_establecimiento integer GENERATED BY DEFAULT AS IDENTITY,
    rbd character varying(10) NOT NULL,
    nombre character varying(150) NOT NULL,
    tipo_local character varying(50) DEFAULT 'Principal'::character varying,
    slep_establecimiento_id integer,
    CONSTRAINT establecimiento_pkey PRIMARY KEY (id_establecimiento),
    CONSTRAINT establecimiento_rbd_key UNIQUE (rbd),
    CONSTRAINT establecimiento_slep_fk FOREIGN KEY (slep_establecimiento_id) REFERENCES public.slep_establecimientos(id)
);
CREATE INDEX idx_establecimiento_slep ON matriculas.establecimiento(slep_establecimiento_id);;
