-- Tabla de acceso por establecimiento (login Google Workspace: correo -> rbd/establecimiento -> rol)
CREATE TABLE matriculas.acceso_establecimiento (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    correo citext NOT NULL,
    id_establecimiento integer NOT NULL,
    rol character varying(50) NOT NULL DEFAULT 'Colegio',
    es_principal boolean DEFAULT false,
    activo boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    CONSTRAINT acceso_establecimiento_pkey PRIMARY KEY (id),
    CONSTRAINT acceso_establecimiento_correo_estab_key UNIQUE (correo, id_establecimiento),
    CONSTRAINT acceso_establecimiento_estab_fkey FOREIGN KEY (id_establecimiento) REFERENCES matriculas.establecimiento(id_establecimiento)
);
CREATE INDEX idx_acceso_correo ON matriculas.acceso_establecimiento(correo);

-- Auditoria (estructura, sin datos del backup)
CREATE TABLE matriculas.auditoria_matricula (
    id_auditoria integer GENERATED BY DEFAULT AS IDENTITY,
    id_matricula integer NOT NULL,
    accion character varying(10) NOT NULL,
    id_usuario integer NOT NULL,
    fecha_accion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    datos_anteriores jsonb,
    datos_nuevos jsonb,
    CONSTRAINT auditoria_matricula_pkey PRIMARY KEY (id_auditoria)
);
CREATE INDEX idx_auditoria_matricula ON matriculas.auditoria_matricula(id_matricula);;
