-- Usuario del sistema de matriculas (interno, con password bcrypt / login google)
CREATE TABLE matriculas.usuario (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY,
    email_institucional character varying(100) NOT NULL,
    nombre character varying(100) NOT NULL,
    rol character varying(50) NOT NULL,
    id_establecimiento integer,
    activo boolean DEFAULT true,
    password_hash character varying(255),
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuario_email_institucional_key UNIQUE (email_institucional),
    CONSTRAINT usuario_id_establecimiento_fkey FOREIGN KEY (id_establecimiento) REFERENCES matriculas.establecimiento(id_establecimiento)
);

-- Estudiante
CREATE TABLE matriculas.estudiante (
    id_estudiante integer GENERATED BY DEFAULT AS IDENTITY,
    run_ipe character varying(20) NOT NULL,
    nombres character varying(100) NOT NULL,
    apellido_paterno character varying(100) NOT NULL,
    apellido_materno character varying(100),
    sexo character varying(20) NOT NULL,
    fecha_nacimiento date NOT NULL,
    domicilio character varying(255) NOT NULL,
    id_apoderado_principal integer,
    latitud character varying(50),
    longitud character varying(50),
    CONSTRAINT estudiante_pkey PRIMARY KEY (id_estudiante),
    CONSTRAINT estudiante_run_ipe_key UNIQUE (run_ipe),
    CONSTRAINT estudiante_id_apoderado_principal_fkey FOREIGN KEY (id_apoderado_principal) REFERENCES matriculas.apoderado(id_apoderado)
);

-- Matricula
CREATE TABLE matriculas.matricula (
    id_matricula integer GENERATED BY DEFAULT AS IDENTITY,
    numero_correlativo integer NOT NULL,
    anio_escolar integer NOT NULL,
    id_estudiante integer NOT NULL,
    id_establecimiento integer NOT NULL,
    fecha_matricula date NOT NULL,
    nivel_ensenanza character varying(100) NOT NULL,
    curso character varying(50) NOT NULL,
    estado character varying(20) DEFAULT 'Activa'::character varying,
    fecha_retiro date,
    motivo_retiro character varying(255),
    observaciones text,
    id_usuario_ejecutor integer NOT NULL,
    cod_tipo_ensenanza integer,
    cod_grado integer,
    letra_curso character varying(5),
    motivo_cambio_curso text,
    CONSTRAINT matricula_pkey PRIMARY KEY (id_matricula),
    CONSTRAINT matricula_folio_unico_por_curso UNIQUE (id_establecimiento, anio_escolar, cod_tipo_ensenanza, curso, numero_correlativo),
    CONSTRAINT matricula_id_estudiante_fkey FOREIGN KEY (id_estudiante) REFERENCES matriculas.estudiante(id_estudiante),
    CONSTRAINT matricula_id_establecimiento_fkey FOREIGN KEY (id_establecimiento) REFERENCES matriculas.establecimiento(id_establecimiento),
    CONSTRAINT matricula_id_usuario_ejecutor_fkey FOREIGN KEY (id_usuario_ejecutor) REFERENCES matriculas.usuario(id_usuario),
    CONSTRAINT matricula_cod_tipo_ensenanza_fkey FOREIGN KEY (cod_tipo_ensenanza) REFERENCES matriculas.catalogo_tipo_ensenanza(codigo),
    CONSTRAINT matricula_cod_grado_fkey FOREIGN KEY (cod_grado) REFERENCES matriculas.catalogo_grado(codigo)
);
CREATE INDEX idx_matricula_estudiante ON matriculas.matricula(id_estudiante);
CREATE INDEX idx_matricula_establecimiento ON matriculas.matricula(id_establecimiento);
CREATE INDEX idx_matricula_anio ON matriculas.matricula(anio_escolar);;
